version: '3.7'

services:
  # -------------------------
  # Airflow (webserver + scheduler + workers)
  # -------------------------
  airflow-webserver:
    build: .
    image: apache/airflow:3.0.0
    restart: always
    depends_on:
      - airflow-scheduler
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=RoDVi5TTOOf0T49W06AKeO1YvzQJeQbpgvHErFt5B2s=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__METRICS__STATSD_ON=True
      - AIRFLOW__METRICS__STATSD_HOST=statsd-exporter
      - AIRFLOW__METRICS__STATSD_PORT=9125
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: api-server

  airflow-scheduler:
    build: .
    image: apache/airflow:3.0.0
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=RoDVi5TTOOf0T49W06AKeO1YvzQJeQbpgvHErFt5B2s=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  # -------------------------
  # StatsD Exporter
  # -------------------------
  statsd-exporter:
    image: prom/statsd-exporter
    ports:
      - "9102:9102"        # Prometheus scrape metrics
      - "9125:9125/udp"    # StatsD UDP port
    command:
      - '--web.listen-address=:9102'
      - '--statsd.listen-udp=:9125'

  # -------------------------
  # Prometheus
  # -------------------------
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9091:9090"


  # -------------------------
  # Grafana
  # -------------------------
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres-db-volume:
  grafana-storage:
